name: Scrape Betting Data

on:
  workflow_dispatch:   # Allow manual run
  schedule:
    - cron: '*/30 * * * *'   # Every 30 minutes (you can change)

jobs:
  scrape-and-deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: write    # <-- Needed to push back changes
      pages: write
      id-token: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'   # or '3.x'

    - name: Install dependencies
      run: |
        pip install requests

    - name: Run scraper
      run: python scraper/scraper.py

    - name: Commit and push changes
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add docs/*.json
        git commit -m "Update betting data" || echo "No changes to commit"
        git push

    - name: Deploy GitHub Pages
      uses: actions/configure-pages@v5

    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: docs

    - name: Deploy to GitHub Pages
      uses: actions/deploy-pages@v4
