name: Betting Scraper

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'  # Schedule to run at midnight every day

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install playwright requests  # Add any additional dependencies
          playwright install  # Install Playwright browser binaries

      - name: Run scraper
        run: |
          python scraper/scraper.py  # Adjust path to your scraper file

      - name: Commit and push changes to docs folder
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add docs/
          git commit -m "Update betting data"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
