name: Betting Scraper

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 */6 * * *' # every 6 hours
  workflow_dispatch: # allow manual button click

jobs:
  scrape:
    runs-on: ubuntu-latest

    permissions:
      contents: write # allow push

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install playwright
          playwright install chromium

      - name: Run scraper
        run: python scraper/scraper.py

      - name: Commit and push updated JSON files
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add docs/
          git commit -m "Update betting data"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
