name: Scrape Betting Data

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 * * * *'  # Runs every hour. Adjust as needed.

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'  # Adjust version as necessary

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        python -m playwright install  # Install Playwright dependencies if needed

    - name: Run Scraper
      run: python scraper/scraper.py

    - name: Commit and Push Data
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "github-actions@users.noreply.github.com"
        git add docs/*.json
        git commit -m "Update betting data"
        git push
